### ISSUE TITLE
have database for publications

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/web-scraping.org#2]
Hi @heyarviind,

looking forward working w/ you on this!

Here's a brief summary:

- Publications listed in JSON file here: https://github.com/hannesdatta/webdata-website/blob/main/data/bib.json
- Please provide filterable view (similar to https://kaggle.com/datasets), with as "categories": Journal (one or more out of five values), Year (numeric value, from 2001 to 2020), and type (scraping, API, or both...).
- Please show this on https://web-scraping.org/docs/databases/publications/

I may be able to implement the other databases myself after seeing this one work out well.

For any questions, please reach out to me!

**Comment by hannesdatta** [comment]
It's best to provide your code via PRs btw

**Comment by heyarviind** [comment]
Cool, I will look into this and will get back to you

**Comment by hannesdatta** [comment]
cool - also let me know whether the array format for the json object works; I could also parse it as new line separated json objects...

**Comment by heyarviind** [comment]
@hannesdatta array format would work just fine.

When no filter is selected, do you want me to show the first few items?

**Comment by hannesdatta** [comment]
Ideally all articles - or the first few with a next page or next button to go through them. 

I hadn't thought of pagination yet but it is probably an issue with potentially 300+ results.

What do u think?

**Comment by heyarviind** [comment]
Okay, I will try implementing pagination on JSON file.

What command are you using to run the project? I am running `hugo server` and it is throwing a few errors

<img width="1512" alt="Screenshot 2022-04-30 at 1 01 36 PM" src="https://user-images.githubusercontent.com/21043614/166096434-5319086a-089b-4c77-b55f-79270f82d004.png">

**Comment by hannesdatta** [comment]
> What command are you using to run the project? I am running hugo server and it is throwing a few errors

great - before running hugo server, you need to run

`npm install`

and 

`npm run start`

you will then have the required libraries, and subsequently it's enough run `hugo server`

see

https://getdoks.org/docs/prologue/quick-start/

**Comment by hannesdatta** [comment]
> Okay, I will try implementing pagination on JSON file.

just to make sure - the pagination will be implemented in js or hugo, NOT in the raw json file, right?

**Comment by heyarviind** [comment]
> > Okay, I will try implementing pagination on JSON file.
> 
> just to make sure - the pagination will be implemented in js or hugo, NOT in the raw json file, right?

it will be implemented in js

**Comment by heyarviind** [comment]
I have implemented the filtering, please review and merge the code 

https://github.com/hannesdatta/webdata-website/pull/4

**Comment by heyarviind** [comment]
I have moved the `bib.json` to `static/data/` folder, this way I can load the data after the page loads, else the page will take a lot of time considering the size of the JSON file.

Now all you have to do is provide filters and source in other pages and the filter will work

<img width="579" alt="Screenshot 2022-04-30 at 3 49 02 PM" src="https://user-images.githubusercontent.com/21043614/166101609-cbdaf107-8552-4664-bd50-184b55a05033.png">

**Comment by hannesdatta** [comment]
Done - see also #5
