### ISSUE TITLE
follow-up design for database

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/web-scraping.org#5]
Hey @heyarviind,

AMAZING & quick job on the database. Thank you so much.

A few short followups:

- the site is so fast that you barely don't have any loading time when clicking on the next page thing. BUT, the downside is, users may not even notice the site has changed! For example, at kaggle, they make use of placeholder effects. Could you implement such a brief placeholder effect that is displayed after clicking on next, to give the user the sign that actually stuff has changed? e.g., using https://getbootstrap.com/docs/5.1/components/placeholders/?
- further, the year tags look quite messy - probably putting it into a container?

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/16557730/166104162-7dc60550-450c-496f-b4e1-78374a830b70.png">

Looking forward to hear your thoughts.

**Comment by heyarviind** [comment]
I have added the shimmer and fixed the layout 

https://github.com/hannesdatta/webdata-website/pull/6

**Comment by hannesdatta** [comment]
- can you make the cards clickable, see #6  for the instructions for the link?
- we noticed the layout doesn't work in dark mode yet

<img width="791" alt="image" src="https://user-images.githubusercontent.com/16557730/166107121-2668dd15-4db6-42cb-b6f8-e5f4a3bfca26.png">


maybe there's a quick fix for that?

**Comment by hannesdatta** [comment]
and pls also briefly comment about ways to search these papers, e.g., by authors or title.

**Comment by hannesdatta** [comment]
if the search isn't feasible within the quote, you can send a follow-up one so we can decide on whether we want that full text search. we're very happy w/ how it looks like so i'd say after the dark mode and the link, we should be done on the first quote.

**Comment by heyarviind** [comment]
> * can you make the cards clickable, see [add shimmer and fix layout #6](https://github.com/hannesdatta/webdata-website/pull/6)  for the instructions for the link?
> * we noticed the layout doesn't work in dark mode yet
> 
> <img alt="image" width="791" src="https://user-images.githubusercontent.com/16557730/166107121-2668dd15-4db6-42cb-b6f8-e5f4a3bfca26.png">
> 
> maybe there's a quick fix for that?

I have fixed it, please review and merge https://github.com/hannesdatta/webdata-website/pull/7

**Comment by heyarviind** [comment]
> and pls also briefly comment about ways to search these papers, e.g., by authors or title.

> if the search isn't feasible within the quote, you can send a follow-up one so we can decide on whether we want that full text search. we're very happy w/ how it looks like so i'd say after the dark mode and the link, we should be done on the first quote.

Authors and text are somewhat similar as they are just strings (authors should be in an array as many items have more than 1 author). For this, I have to do the text search in both with the filters selected. This gonna cost some performance if the JSON file gets bigger.

Let me figure it out and I will get back to you on this.

**Comment by hannesdatta** [comment]
perfect - thanks. 

let us consider this job done for now (unless I discover very minor things) & then we can create some more issues over the next few weeks and we can have you work on those then under a new 'contract'.

makes sense?

really thanks a lot for your professional and fast help on this.

**Comment by heyarviind** [comment]
> perfect - thanks.
> 
> let us consider this job done for now (unless I discover very minor things) & then we can create some more issues over the next few weeks and we can have you work on those then under a new 'contract'.
> 
> makes sense?
> 
> really thanks a lot for your professional and fast help on this.

Sounds good to me 😋

**Comment by hannesdatta** [comment]
New database up & running :)
