### ISSUE TITLE
issues on mobile phone

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/web-scraping.org#8]
hey @heyarviind,

did you test the db on a mobile phone? just tried w/ my iPhone and the screen gets stuck w/ the grey cards ("loading").

**Comment by heyarviind** [comment]
let me check

**Comment by heyarviind** [comment]
@hannesdatta is it happening every time you refresh the page... what browser are you using?

I am not able to reproduce this... Can you provide more information on this?

**Comment by hannesdatta** [comment]
it works on firefox and chrome - and it does not on safari.

![IMG_824FDA186579-1](https://user-images.githubusercontent.com/16557730/166110230-3bb28985-23aa-48ff-92b4-d280b7fb535d.jpeg)

**Comment by hannesdatta** [comment]
@jboegershausen - can you try w/ ur iPhone pls using safari - does the page render for you?

**Comment by heyarviind** [comment]
its working on my safari 🤨!

[Uploading 166110319...]

**Comment by heyarviind** [comment]
its working on my safari 🤨

![image](https://user-images.githubusercontent.com/21043614/166110345-140da497-74f4-4789-9cbb-4ec4fdd59068.png)

**Comment by hannesdatta** [comment]
can't reproduce on another phone, so prob it's a bug on my phone. we can close this.
